

name: "Generate package versions"
on:
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Update files
      run: |
        sleep $((RANDOM % 60))
        ./generate-current.sh
        ./generate-versions.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update version data
